# Generated by Django 3.1.3 on 2020-11-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task',
            new_name='task_list',
        ),
    ]
